services:
  macos:
    image: dockurr/macos
    container_name: jordanm88-mac14
    environment:
      VERSION: "14"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "100G"
      
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - '8006:8006'
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /home/umbrel/umbrel/app-data/jordanm88-mac14/data:/storage
    restart: unless-stopped
    stop_grace_period: 2m